name: Deploy to GitHub Pages

on:
  push:
    branches: [main]  # Triggers the workflow on push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Use a Node.js version appropriate for your project

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Deploy to GitHub Pages
      run: npm run deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        # GITHUB_TOKEN is automatically available for actions. 
        # If additional tokens or secrets (such as custom deploy hooks) are needed, add them in the repository secrets.

